displayName: ELLIO Traefik Middleware Plugin
type: middleware
import: github.com/ELLIO-Technology/ELLIO-Traefik-Middleware-Plugin
summary: Dynamic IP blocklisting/allowlisting middleware using ELLIO External Dynamic Lists (EDL)
testData:
  bootstrapToken: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2FwaS5wbGF0Zm9ybS5lbGxpby50ZWNoIiwic3ViIjoiZGVwbG95bWVudDpiYTY3MTBhNi01YjVjLTQxMjYtYTExZC1mZjhkNGRhOGM3YTYiLCJhdWQiOiJlZGxfYm9vdHN0cmFwIiwid29ya3NwYWNlX2lkIjoiZDJmMmRmYjctYWVjNC00MzJjLWExZWQtZWM0MjU4M2U1MTAxIiwiZGVwbG95bWVudF9pZCI6ImJhNjcxMGE2LTViNWMtNDEyNi1hMTFkLWZmOGQ0ZGE4YzdhNiIsImNvbXBvbmVudF90eXBlIjoiZWxsaW9fdHJhZWZpa19taWRkbGV3YXJlX3BsdWdpbiIsImt2ZXIiOjEsImlhdCI6MTc1NzE1NDMyOX0.h-q825TE7wxvtw1ekx9TLDdFUdIBJre1NqxIliIpKqmkiQOwQtBudKRK6gZU1R8hFOeu_1Ry1-KShUcfdtFNBw" # Placeholder for Traefik plugin validation


iconPath: ./assets/icon.png
bannerPath: ./assets/banner.png
