# To see all available options, please visit the docs:
# https://docs.digpangolin.com/self-host/advanced/config-file

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.istelnetdead.com"

app:
    dashboard_url: "https://pangolin.istelnetdead.com"
    log_level: "info"

domains:
    domain1:
        base_domain: "istelnetdead.com"
        cert_resolver: "letsencrypt"

server:
    secret: "Bq0OTRpFPnCbhqxDtqiYqmCfsQkI9orj"
    cors:
        origins: ["https://pangolin.istelnetdead.com"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true

traefik:
    additional_middlewares: ["ellio-edl@file"]
